spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
