spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

analyzer:
  kafka:
    topics:
      snapshots: telemetry.snapshots.v1
      hubs: telemetry.hubs.v1

kafka:
  bootstrap-servers: localhost:9092

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
