syntax = "proto3";

package telemetry.service;

option java_multiple_files = true;
option java_package = "ru.yandex.practicum.grpc.telemetry.service";

import "google/protobuf/empty.proto";
import "telemetry/messages/hub_event.proto";
import "telemetry/messages/sensor_event.proto";

service CollectorControllerService {
  rpc CollectSensorEvent(telemetry.message.event.SensorEventProto) returns (google.protobuf.Empty);
  rpc CollectHubEvent(telemetry.message.event.HubEventProto) returns (google.protobuf.Empty);
}
